### login to a specific account
POST {{$dotenv url}}/api/auth/login
Content-Type: application/json

{
  "username": "{{$dotenv username}}",
  "password": "{{$dotenv password}}"
}

### forgot password route
POST {{$dotenv url}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "{{$dotenv email}}"
}

### updates the own user
POST {{$dotenv url}}/api/auth/update-self
Authorization: Bearer {{$dotenv jwt2}}
Content-Type: application/json

{
  "currentPassword": "{{$dotenv password}}",
  "email": "{{$dotenv email}}"
}

### gets information about the token
GET {{$dotenv url}}/api/auth/whoami
Authorization: Bearer {{$dotenv jwt}}

### gets information about the secondary token
GET {{$dotenv url}}/api/auth/whoami
Authorization: Bearer {{$dotenv jwt2}}

### creates a new user with a invite token
POST {{$dotenv url}}/api/auth/register
Content-Type: application/json

{
  "username": "{{$dotenv username}}",
  "password": "{{$dotenv password}}",
  "token": "{{$dotenv invite_token}}"
}

### invites an existing user via invite token
POST {{$dotenv url}}/api/auth/invite
Content-Type: application/json
Authorization: Bearer {{$dotenv jwt2}}

{
  "token": "367e20ae5b0de8b0ac440bc0dfc0d46a"
}

### changes the password for the current login token
POST {{$dotenv url}}/api/auth/update-password
Content-Type: application/json
Authorization: Bearer {{$dotenv jwt2}}

{
  "oldPassword": "",
  "newPassword": ""
}

### performs a search for a player, retrieves id, name, guid
POST {{$dotenv url}}/api/auth/search-player
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "guid": "984a4d8aefd4494fa6e8d35de3151dd5"
}


### retrieves all bindings from the current user
GET {{$dotenv url}}/api/auth/binding
Authorization: Bearer {{$dotenv jwt}}

### assigns a player to this user
POST {{$dotenv url}}/api/auth/binding
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "playerId": 1
}

### removes a player binding from the current user
DELETE {{$dotenv url}}/api/auth/binding/1
Authorization: Bearer {{$dotenv jwt}}