@pluginName=showcase
@instanceId=2

### gets a specific route from a plugin
GET {{$dotenv url}}/api/plugins/{{instanceId}}/{{pluginName}}/metrics


### lists all available instances
OPTIONS {{$dotenv url}}/api/instances
Authorization: Bearer {{$dotenv jwt}}