@pluginName=test
@instanceId=2

### gets a specific route from a plugin
GET {{$dotenv url}}/api/plugins/{{instanceId}}/{{pluginName}}/echo
Content-Type: application/json

{
  "foo": "bar"
}


### lists all available instances
OPTIONS {{$dotenv url}}/api/instances
Authorization: Bearer {{$dotenv jwt}}