@id=1

### create a new instance
POST {{$dotenv url}}/api/instances
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "host": "{{$dotenv instance_host}}",
  "port": {{$dotenv instance_port}},
  "password": "{{$dotenv instance_pass}}"
}

### create a new instance
POST {{$dotenv url}}/api/instances
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "host": "{{$dotenv instance1_host}}",
  "port": {{$dotenv instance1_port}},
  "password": "{{$dotenv instance1_pass}}"
}

### lists all available instances
GET {{$dotenv url}}/api/instances
Authorization: Bearer {{$dotenv jwt}}


### stops an instance by its id
PATCH {{$dotenv url}}/api/instances/{{id}}/stop
Authorization: Bearer {{$dotenv jwt}}

### starts an instance by its id
PATCH {{$dotenv url}}/api/instances/{{id}}/start
Authorization: Bearer {{$dotenv jwt}}

### deletes an instance
DELETE {{$dotenv url}}/api/instances/{{id}}
Authorization: Bearer {{$dotenv jwt}}


### lists all users for this instance
GET {{$dotenv url}}/api/instances/{{id}}/users
Authorization: Bearer {{$dotenv jwt}}

### reads all invite for new users
GET {{$dotenv url}}/api/instances/{{id}}/users/invite
Authorization: Bearer {{$dotenv jwt}}


### creates an invite for a new user
POST {{$dotenv url}}/api/instances/{{id}}/users/invite
Authorization: Bearer {{$dotenv jwt}}