@instanceId=1
@mapIndex=1

### retrieve a list of available maps
GET {{$dotenv url}}/api/instances/{{instanceId}}/maps
Authorization: Bearer {{$dotenv jwt}}

### retrieves the current map index
GET {{$dotenv url}}/api/instances/{{instanceId}}/maps/current
Authorization: Bearer {{$dotenv jwt}}


### sets the next map index
POST {{$dotenv url}}/api/instances/{{instanceId}}/maps/0/next
Authorization: Bearer {{$dotenv jwt}}

### starts the next round
POST {{$dotenv url}}/api/instances/{{instanceId}}/maps/nextRound
Authorization: Bearer {{$dotenv jwt}}

