@instanceId=1
@pluginId=1

### retrieve a list of created plugins
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins
Authorization: Bearer {{$dotenv jwt}}

### retrieve a list of useable plugins
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins/available
Authorization: Bearer {{$dotenv jwt}}

### adds a new plugin to the server
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "identifier": "test"
}

### retrieves a single plugin
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}
Authorization: Bearer {{$dotenv jwt}}

### starts a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/start
Authorization: Bearer {{$dotenv jwt}}

### stops a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/stop
Authorization: Bearer {{$dotenv jwt}}