@instanceId=6
@pluginId=6
@uuid=2978958113a65be4f18e7f48e566db43

### retrieve a list of useable plugins
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins
Authorization: Bearer {{$dotenv jwt}}

### retrieves a single plugin
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}
Authorization: Bearer {{$dotenv jwt}}

### deletes a plugin
DELETE {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}
Authorization: Bearer {{$dotenv jwt}}

### updates the configuration of a plugin
PATCH {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/config
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "fooKey": "something",
  "arrayKey": [{
    "nestedStringKey": "something else",
    "arrayRecursive": [{
      "nestedStringKey2": "123",
      "nestedStringNumber2": 123
    }, {
      "nestedStringKey2": "1234",
      "nestedStringNumber2": 1234
    }]
  }]
}

### starts a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/start
Authorization: Bearer {{$dotenv jwt}}

### stops a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/stop
Authorization: Bearer {{$dotenv jwt}}

### retrieves plugins in store
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins/store
Authorization: Bearer {{$dotenv jwt}}

### downloads a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/store/{{uuid}}
Authorization: Bearer {{$dotenv jwt}}