@instanceId=2
@pluginId=1
@uuid=2978958113a65be4f18e7f48e566db43

### retrieve a list of useable plugins
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins
Authorization: Bearer {{$dotenv jwt}}

### retrieves a single plugin
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}
Authorization: Bearer {{$dotenv jwt}}

### deletes a plugin
DELETE {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}
Authorization: Bearer {{$dotenv jwt}}

### updates the configuration of a plugin
PATCH {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/config
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "foo": "non default"
}

### starts a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/start
Authorization: Bearer {{$dotenv jwt}}

### stops a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/{{pluginId}}/stop
Authorization: Bearer {{$dotenv jwt}}

### retrieves plugins in store
GET {{$dotenv url}}/api/instances/{{instanceId}}/plugins/store
Authorization: Bearer {{$dotenv jwt}}

### downloads a plugin
POST {{$dotenv url}}/api/instances/{{instanceId}}/plugins/store/{{uuid}}
Authorization: Bearer {{$dotenv jwt}}