@userId=3


### lists all users for this instance
GET {{$dotenv url}}/api/users
Authorization: Bearer {{$dotenv jwt}}

### lists a single user
GET {{$dotenv url}}/api/users/{{userId}}
Authorization: Bearer {{$dotenv jwt}}
