@id=6

### lists all available variables
GET {{$dotenv url}}/api/instances/{{id}}/vars
Authorization: Bearer {{$dotenv jwt}}

### gets a list of variables which can be set or get
GET {{$dotenv url}}/api/instances/{{id}}/vars/options
Authorization: Bearer {{$dotenv jwt}}

### updates a single variable
PATCH {{$dotenv url}}/api/instances/{{id}}/vars
Authorization: Bearer {{$dotenv jwt}}
Content-Type: application/json

{
  "serverDescription": "Hello World!"
}