export enum WorkerState {
  UNKNOWN = "WORKERSTATE_UNKNOWN",
  STOP = "WORKERSTATE_STOP",
  INIT = "WORKERSTATE_INIT",
  READY = "WORKERSTATE_READY"
}

export enum PluginState {
  RUNNING = "PLUGINSTATE_RUNNING",
  NOT_RUNNING = "PLUGINSTATE_NOT_RUNNING"
}