@url=http://127.0.0.1:8000
@id=1
@jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpbnN0YW5jZSI6bnVsbCwicm9vdCI6dHJ1ZSwicGVybWlzc2lvbiI6ImZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmOmZmIn1dLCJpYXQiOjE1OTAyNTUxMjB9.7GswrzDQEdjWyD3dr13WTpaKU1PKEbnaK2urUpoHhtY

### create a new instance
POST {{url}}/api/instances
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "host": "multivitamin.wtf",
  "port": 47200,
  "password": "saft"
}

### lists all available instances
GET {{url}}/api/instances
Authorization: Bearer {{jwt}}


### stops an instance by its id
PATCH {{url}}/api/instances/{{id}}/stop
Authorization: Bearer {{jwt}}

### starts an instance by its id
PATCH {{url}}/api/instances/{{id}}/start
Authorization: Bearer {{jwt}}

### deletes an instance
DELETE {{url}}/api/instances/{{id}}
Authorization: Bearer {{jwt}}